apiVersion: apps/v1
kind: Deployment
metadata:
  name: axionui
spec:
  replicas: 2
  selector:
    matchLabels:
      app: axionui
  template:
    metadata:
      labels:
        app: axionui
    spec:
      containers:
      - name: axionui
        image: acraxionservice.azurecr.io/axionui:v1
        ports:
        - containerPort: 80
