apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ui-ingress
  labels:
    app.kubernetes.io/name: ui-ingress
spec:
  ingressClassName: nginx
  rules:
  - host: aknsp.shop
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: axionuiservice
            port: 
              number: 80


